import '../models/study_place.dart';

class PlaceService {
  Future<List<StudyPlace>> fetchPlaces() async {
    await Future.delayed(const Duration(milliseconds: 600));

    return [
      StudyPlace(
        id: '1',
        name: 'Villa Savonarola (Biblioteca Comunale di Portici)',
        address: 'Corso Giuseppe Garibaldi, 200',
        city: 'Portici',
        category: 'Biblioteca',
        googlePlaceId: 'ChIJ____nAGnOxMRmtjQRkv9Vto',
        rating: 0,
        reviewsCount: 0,
        hasWifi: true,
        hasPowerOutlets: false,
        isQuiet: true,
        isFree: true,
        imageUrl: '',
        description:
            'Biblioteca comunale di Portici, ambiente adatto allo studio.',
        tags: ['Silenzioso', 'Wi-Fi', 'Gratis'],
        isFavorite: false,
      ),
      StudyPlace(
        id: '2',
        name: 'Villa Bruno (Biblioteca Comunale Padre Alagi)',
        address: 'Via Cavalli di Bronzo, 22',
        city: 'San Giorgio a Cremano',
        category: 'Biblioteca',
        googlePlaceId: 'ChIJd0LVa1GmOxMRwnkwmL03w1E',
        rating: 0,
        reviewsCount: 0,
        hasWifi: false,
        hasPowerOutlets: false,
        isQuiet: true,
        isFree: true,
        imageUrl: '',
        description: 'Spazio culturale con ambiente tranquillo per lo studio.',
        tags: ['Silenzioso', 'Gratis'],
        isFavorite: false,
      ),
      StudyPlace(
        id: '3',
        name: 'Biblioteca Nazionale di Napoli Vittorio Emanuele III',
        address: 'Piazza del Plebiscito, 1',
        city: 'Napoli',
        category: 'Biblioteca',
        googlePlaceId: 'ChIJjRwE9VIIOxMRslgLEKOUvc8',
        rating: 0,
        reviewsCount: 0,
        hasWifi: true,
        hasPowerOutlets: false,
        isQuiet: true,
        isFree: true,
        imageUrl: '',
        description: 'Biblioteca storica nazionale nel centro di Napoli.',
        tags: ['Silenzioso', 'Wi-Fi', 'Gratis'],
        isFavorite: false,
      ),
      StudyPlace(
        id: '4',
        name: 'Biblioteca Universitaria di Napoli (BUN)',
        address: 'Via Giovanni Paladino, 39',
        city: 'Napoli',
        category: 'Biblioteca',
        googlePlaceId: 'ChIJDS9M_EMIOxMRR65CF6AfyrA',
        rating: 0,
        reviewsCount: 0,
        hasWifi: true,
        hasPowerOutlets: false,
        isQuiet: true,
        isFree: true,
        imageUrl: '',
        description: 'Biblioteca universitaria nel centro storico di Napoli.',
        tags: ['Silenzioso', 'Wi-Fi', 'Gratis'],
        isFavorite: false,
      ),
      StudyPlace(
        id: '5',
        name: 'BRAU Biblioteca di Ricerca di Area Umanistica',
        address: 'Piazza Bellini, 60',
        city: 'Napoli',
        category: 'Biblioteca',
        googlePlaceId: 'ChIJtzil2UIIOxMRT6-a5A55w1s',
        rating: 0,
        reviewsCount: 0,
        hasWifi: true,
        hasPowerOutlets: false,
        isQuiet: true,
        isFree: true,
        imageUrl: '',
        description: 'Biblioteca di ricerca dell’Università Federico II.',
        tags: ['Silenzioso', 'Wi-Fi', 'Gratis'],
        isFavorite: false,
      ),
      StudyPlace(
        id: '6',
        name: 'Biblioteca Pubblica Comunale Benedetto Croce',
        address: 'Via Francesco de Mura, 2A',
        city: 'Napoli',
        category: 'Biblioteca',
        googlePlaceId: 'ChIJbzFF2_kIOxMRgpmiqKqJNlM',
        rating: 0,
        reviewsCount: 0,
        hasWifi: true,
        hasPowerOutlets: false,
        isQuiet: true,
        isFree: true,
        imageUrl: '',
        description: 'Biblioteca comunale del quartiere Vomero.',
        tags: ['Silenzioso', 'Wi-Fi', 'Gratis'],
        isFavorite: false,
      ),
      StudyPlace(
        id: '7',
        name: 'The Spark Creative Hub',
        address: 'Via degli Acquari (Piazza Bovio)',
        city: 'Napoli',
        category: 'Spazio studio',
        googlePlaceId: 'ChIJYXrNArMJOxMR0PwmAr62eNQ',
        rating: 0,
        reviewsCount: 0,
        hasWifi: true,
        hasPowerOutlets: true,
        isQuiet: false,
        isFree: false,
        imageUrl: '',
        description: 'Spazio di coworking, libreria e sala studio.',
        tags: ['Wi-Fi', 'Prese', 'Gruppi'],
        isFavorite: false,
      ),
      StudyPlace(
        id: '8',
        name: 'Biblioteca della Fondazione Banco di Napoli',
        address: 'Via dei Tribunali, 213',
        city: 'Napoli',
        category: 'Biblioteca',
        googlePlaceId: 'ChIJLzGMMxUIOxMRu5kJoA3LOCU',
        rating: 0,
        reviewsCount: 0,
        hasWifi: true,
        hasPowerOutlets: false,
        isQuiet: true,
        isFree: true,
        imageUrl: '',
        description: 'Biblioteca storica della Fondazione Banco di Napoli.',
        tags: ['Silenzioso', 'Wi-Fi', 'Gratis'],
        isFavorite: false,
      ),
      StudyPlace(
        id: '9',
        name: 'Biblioteca Comunale Agostino Collina',
        address: 'Via Beato Leonardo Murialdo, 7',
        city: 'Napoli',
        category: 'Biblioteca',
        googlePlaceId: 'ChIJ76BDN_enOxMRZa0ma_AT9kI',
        rating: 0,
        reviewsCount: 0,
        hasWifi: true,
        hasPowerOutlets: false,
        isQuiet: true,
        isFree: true,
        imageUrl: '',
        description: 'Biblioteca comunale nella zona Poggioreale.',
        tags: ['Silenzioso', 'Wi-Fi', 'Gratis'],
        isFavorite: false,
      ),
      StudyPlace(
        id: '10',
        name: 'Biblioteca Di Napoli Antonio Labriola',
        address: 'Piazza Giambattista Pacichelli, 10',
        city: 'Napoli',
        category: 'Biblioteca',
        googlePlaceId: 'ChIJi_X4j6GnOxMRMTDehTWfa-U',
        rating: 0,
        reviewsCount: 0,
        hasWifi: false,
        hasPowerOutlets: false,
        isQuiet: true,
        isFree: true,
        imageUrl: '',
        description: 'Biblioteca comunale della zona San Giovanni a Teduccio.',
        tags: ['Silenzioso', 'Gratis'],
        isFavorite: false,
      ),
      StudyPlace(
        id: '11',
        name: 'Biblioteca Le Nuvole (Centro Alberto Hurtado)',
        address: 'Viale della Resistenza, 27',
        city: 'Napoli',
        category: 'Biblioteca',
        googlePlaceId: 'ChIJoYU2hMMHOxMRYUrG6GV7dP4',
        rating: 0,
        reviewsCount: 0,
        hasWifi: true,
        hasPowerOutlets: false,
        isQuiet: true,
        isFree: true,
        imageUrl: '',
        description: 'Centro culturale con spazio dedicato allo studio.',
        tags: ['Silenzioso', 'Wi-Fi', 'Gratis'],
        isFavorite: false,
      ),
      StudyPlace(
        id: '12',
        name: 'Biblioteca Comunale Domenico Severino',
        address: 'Via Nuova Dietro la Vigna, 31',
        city: 'Napoli',
        category: 'Biblioteca',
        googlePlaceId: 'ChIJI_iy2jMGOxMR5vA-zebifw8',
        rating: 0,
        reviewsCount: 0,
        hasWifi: false,
        hasPowerOutlets: false,
        isQuiet: true,
        isFree: true,
        imageUrl: '',
        description: 'Biblioteca comunale della zona Piscinola.',
        tags: ['Silenzioso', 'Gratis'],
        isFavorite: false,
      ),
    ];
  }
}
