// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRSArKt2vOecp9fw021AM5zI1BWZPxLUI',
    appId: '1:583002313798:web:29a470a1c4bc8b09b4e647',
    messagingSenderId: '583002313798',
    projectId: 'dove-studiamo-28ad5',
    authDomain: 'dove-studiamo-28ad5.firebaseapp.com',
    storageBucket: 'dove-studiamo-28ad5.firebasestorage.app',
    measurementId: 'G-N2BR6V2M4W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzGeLtAgBaZedfUC73qivNJSKDune5Ea0',
    appId: '1:583002313798:android:593203ce60de8282b4e647',
    messagingSenderId: '583002313798',
    projectId: 'dove-studiamo-28ad5',
    storageBucket: 'dove-studiamo-28ad5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAPv7p3H9HsjPjFq7uMkUz3OwguvoyW48',
    appId: '1:583002313798:ios:3a1847a2ad7ba30fb4e647',
    messagingSenderId: '583002313798',
    projectId: 'dove-studiamo-28ad5',
    storageBucket: 'dove-studiamo-28ad5.firebasestorage.app',
    iosBundleId: 'com.example.doveStudiamo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAPv7p3H9HsjPjFq7uMkUz3OwguvoyW48',
    appId: '1:583002313798:ios:3a1847a2ad7ba30fb4e647',
    messagingSenderId: '583002313798',
    projectId: 'dove-studiamo-28ad5',
    storageBucket: 'dove-studiamo-28ad5.firebasestorage.app',
    iosBundleId: 'com.example.doveStudiamo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRSArKt2vOecp9fw021AM5zI1BWZPxLUI',
    appId: '1:583002313798:web:37f887d81ece2a1cb4e647',
    messagingSenderId: '583002313798',
    projectId: 'dove-studiamo-28ad5',
    authDomain: 'dove-studiamo-28ad5.firebaseapp.com',
    storageBucket: 'dove-studiamo-28ad5.firebasestorage.app',
    measurementId: 'G-XM32T63B4Y',
  );
}
